name: koda
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.3.8"


dependencies:
  flutter:
    sdk: flutter
  
  #yall put your dependencies here:
  page_transition: ^2.0.9
  cupertino_icons: ^1.0.5
  http: ^0.13.5
  firebase: ^9.0.3
  firebase_core: ^2.2.0
  firebase_auth: ^4.1.2
  firebase_ui_auth: ^1.0.6
  cloud_firestore: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/